version: '3'

services:
  asterisk:
    image: mlan/asterisk
    container_name: sip-asterisk
    network_mode: host
    volumes:
      - ./config:/etc/asterisk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "asterisk -rx 'core show version' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
   

volumes:
  asterisk-logs:

networks:
  default:
    driver: bridge
